description = "检查当前分支是否与远端同步（基于 scripts/git_check_sync.sh）"

prompt = """
你现在要完成一次 Git 分支同步性检查。

请先阅读以下脚本输出（已自动执行）：
```text
!{npm run --silent git:check-sync}
````

要求：

1. 用简洁中文总结：是否同步、ahead/behind、工作区状态（未跟踪/未提交）。
2. 若发现异常，列出可执行的修复建议（不执行破坏性命令）。如果没有异常，则不用执行这一步。
   """
