description = "将远端数据同步到本地分支。（可选参数为force，是否强制覆盖）"

prompt = """
目标：将远端分支的数据同步到本地分支，以下是执行结果。请根据执行结果，按照行动序列操作。

执行记录：
```text
!{npm run --silent git:pull-from-remote {{args}}}
````

行动序列：
1. 回复用户将尝试从远端拉取更新到当前分支；
2. 分析上述的执行记录。
3. 根据执行结果反馈：
    - 若提示“已从远端 fast-forward 拉取更新”或“本地与远端一致”，告知用户已完成；
    - 若失败且错误为“本地分支领先（ahead）”，提示用户先确认是否需要保留本地分支；
    - 若失败为工作区未提交或其他 Git 报错，分析报错并给出修复建议（提交/暂存/检查网络与权限），等待用户处理；
4. 如果用户确认“不需要保留本地分支”，再执行【执行这个npm指令】 npm run git:pull-from-remote force（此时带上 force 参数），并将结果告知用户；
5. 如果用户表示“需要保留本地分支”，则结束本次执行并提示用户自行处理（如创建新分支、保留提交、手动合并等）；
6. 全部行动完成后，等待用户下一步指令。
  """