description = "通过本地封装脚本执行一次 SQL 任务（参数为 数据库名和sql语句）"

prompt = """
以下是执行数据库脚本后返回的结果：
```text
!{npm run --silent sql:exec {{args}}}
````

请你：

1. 将脚本返回的JSON结果转换为Markdown表格并输出。
2. 对记录的SQL语句进行逻辑和结构分析，向用户解释其工作原理。
3. 如果用户提出修改意见，请根据意见更新SQL语句。
4. 使用更新后的SQL重新执行步骤1-4。
5. 等待用户的下一步指示。
  """