description = "当本地无 XML 时，走 MCP 拉取 Jira 并生成总结后写入 Notion，变量是工单号"

prompt = """
总述：通过 MCP Chrome浏览器工具拉取jira工单并总结，然后写入 Notion。

1) 调用mcp_chrome的浏览器工具访问 http://jira.mailtech.cn/si/jira.issueviews:issue-xml/{工单号}/{工单号}.xml 并获取其XML内容。
2) 基于下面的模板规范生成 Markdown 总结。
3) 确认我满意后，调用 Notion MCP 在我的私有空间创建页面，标题使用总结标题。

执行记录（执行后会生成模板）：
```text
!{npm run --silent mcp:sum:jira {{args}}}
````

详细要求：

1. 指令将返回总结的模板规范。在生成最终文档前，如果发现缺少必要信息，请先与用户沟通补齐。
2. 根据模板和XML内容输出markdown格式的知识库文档，并请明确咨询用户，确认是否满意，并告知修正完成后将会写入一个notion页面中。若用户回复不满意，根据用户的反馈意见进行修改并重新输出。
3. 若用户满意，则调用 Notion mcp的页面创建工具，将 Markdown 格式的笔记内容写入一个新的私有页面，页面标题使用总结结果中的标题。
4. 如果用户提供了多个工单，请将任务串行处理，一次一个。
5. 若操作失败，请复核输入参数与权限后重试该指令；持续失败时，记录报错信息并向开发者反馈。
  """