description = "根据工单号生成总结提示词（前提：本地已存在 {工单号}.xml），变量为工单号"

prompt = """
任务：对指定工单进行知识库总结（本地已下载 XML）。

执行记录（包含提示词文件路径等信息）：
```text
!{npm run --silent sum:jira {{args}}}
````

请你：

1. 从上面的执行输出中提取“提示词文件路径”（包含已拼接的工单内容）。在 git bash 中可用 `test -s <路径>` 校验文件存在且非空；若需与 Windows 原生工具交互，可用 `cygpath -w <路径>` 转换为 Windows 路径。特别注意：当调用你自己的文件工具（如 ReadFile, WriteFile 等）时，必须提供工具所要求的绝对路径格式。例如，在Windows环境下，应使用 `E:\\AI\\git_repo\\CLI_auto_tools\\prompt\\temp\\CS-370665_prompt.md` 这样的标准路径，否则将导致工具执行失败。
2. 打开并快速审阅文件内容，确认工单标题、描述、评论等信息已正确拼接。
3. 如需补充上下文（例如期望产出格式、读者对象、边界条件），请直接编辑该提示词文件并保存，保留原有工单关键信息不丢失。
4. 在后续步骤中，前往 `npm run help` 选择与当前目标匹配的自动化指令（如总结、评审、生成变更说明等），并在支持的情况下将“提示词文件路径”作为输入参数传入该指令。
5. 若一次性处理多个工单，请确认文件内容是否按预期顺序与分隔格式拼接；必要时拆分为多个提示词文件分别使用。
6. 若未生成路径或路径无效，请复核输入参数与权限后重试该指令；持续失败时，记录报错信息并向开发者反馈以便排查。
   """
